apiVersion: v1
kind: Service
metadata:
  name: sabadaco-mongo
  labels:
    app: sabadaco-mongo
spec:
  type: ClusterIP
  selector:
    app: sabadaco-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP
